// examples/sokol/main_array.cpp — kiln-sokol-array: one texture array that kiln assembles at load time
// from six separately cooked PNG tiles (docs/design/runtime-texture-arrays.md), drawn through sokol_gfx
// as a floor of tiles. sokol_app owns the loop, as in kiln-sokol. The steps a host takes are numbered.
#include "cli.h"
#include "example_app.h"
#include "no_crash_dialogs.h"
#include "readback.h"
#include "sokol_adapter.h"

#include <kiln/assets.h>
#include <kiln/log.h>
#if KILN_SOKOL_HAS_COOK
#include <kiln/cook/provider.h>
#endif

#include "sokol_app.h"
#include "sokol_glue.h"
#include "sokol_log.h"
// Generated by sokol-shdc from array.glsl: floor_shader_desc(), floor_params_t and the slot constants.
#include "array.glsl.h"

using namespace kiln;
using namespace kiln::sk;

namespace {

// The array's layers: each is an ordinary texture name, cooked and stored on its own.
constexpr StrView kLayers[] = {"tiles:tile0.png", "tiles:tile1.png", "tiles:tile2.png",
                               "tiles:tile3.png", "tiles:tile4.png", "tiles:tile5.png"};
constexpr f32 kCols = 12, kRows = 7;

struct App {
    ex::Options o;
    bool verify  = false;
    int exitCode = 0;

    Adapter adapter{};
    SokolAdapter* sa = nullptr;
    Context* ctx     = nullptr;
    bool provider    = false;

    TextureHandle tiles;
    TextureHandle own[countof(kLayers)] = {}; ///< --verify: each tile as a texture of its own

    sg_shader shader{};
    sg_pipeline pipeline{};
    sg_sampler sampler{};

    bool settledOnce = false;
    bool quitting    = false; ///< sapp_request_quit() still runs frames until the app ends
    double startMs   = 0;
};

/// --dump <file.png>, --verify and --help. Returns -1 to run, else the exit code.
int parse(int argc, char** argv, App* app) {
    ex::Options& o           = app->o;
    cli::Option const opts[] = {
        {.name = "--dump",
         .arg  = "<file.png>",
         .help = "no interaction: wait until the array has loaded, write the frame, exit",
         .str  = &o.dump},
        {.name = "--verify",
         .help = "no interaction: read the array back and compare every layer and level with the tile "
                 "loaded as a texture of its own; exit 1 on a difference", .flag = &app->verify},
    };
    cli::Spec const spec{
        .program  = "kiln-sokol-array",
        .synopsis = "[--dump <file.png>] [--verify]",
        .options  = {opts, countof(opts)},
        .footer   = "Draws a floor of tiles from one texture array that kiln assembles from\n"
                    "examples/assets/tiles/tile0.png ... tile5.png. Edit a tile (or rerun make_tiles.py)\n"
                    "and the array reloads. Esc quits.",
    };
    cli::Result const args = cli::parse(spec, argc, argv);
    if (args.help) return 0;
    if (!args.ok) {
        cli::usage(spec, stderr);
        return 2;
    }
    o.store     = ex::store_dir();
    o.roots[0]  = Root{StrView("tiles"), StrView(ex::asset_dir("tiles"))};
    o.rootCount = 1;
    o.offscreen = o.dump != nullptr || app->verify;
    return -1;
}

void log_array(Context* ctx, TextureHandle h) {
    TextureInfo const ti = texture_info(ctx, h);
    KILN_INFO("array", "%u layers of %s %ux%u, %u levels, version %u", ti.desc.layers,
              format_name(ti.desc.format), ti.desc.width, ti.desc.height, ti.desc.levels, ti.version);
}

bool settled(App const& app) {
    if (!ex::settled(state(app.ctx, app.tiles))) return false;
    if (!app.verify || state(app.ctx, app.tiles) == State::Failed) return true;
    for (TextureHandle h : app.own)
        if (h.is_null() || !ex::settled(state(app.ctx, h))) return false;
    return true;
}

bool read_texture_fn(void* user, GpuObject obj, TextureDesc const& desc, Vec<u8>* out) {
    sg_view const view = sokol_texture(static_cast<SokolAdapter const*>(user), obj);
    return view.id && read_texture(sg_query_view_image(view), desc, *out);
}

/// One frame of the floor into `pass` (the swapchain, or the --dump target).
void draw_floor(App& app, sg_pass const& pass) {
    sg_begin_pass(&pass);
    // Until Ready, gpu_object() serves the array placeholder of its kind.
    sg_view const tex = sokol_texture(app.sa, gpu_object(app.ctx, app.tiles));
    if (tex.id) {
        floor_params_t const p{
            .grid = {kCols, kRows, f32(max(texture_info(app.ctx, app.tiles).desc.layers, 1u)), 0}
        };
        sg_bindings b{};
        b.views[VIEW_tiles] = tex;
        b.samplers[SMP_smp] = app.sampler;
        sg_apply_pipeline(app.pipeline);
        sg_apply_bindings(&b);
        sg_range const ub{&p, sizeof p};
        sg_apply_uniforms(UB_floor_params, &ub);
        sg_draw(0, 3, 1);
    }
    sg_end_pass();
}

/// Renders one more frame into an image of its own and writes it as a PNG.
bool dump(App& app, int w, int h) {
    sg_image_desc cd{};
    cd.usage.color_attachment = true;
    cd.width                  = w;
    cd.height                 = h;
    cd.pixel_format           = sglue_environment().defaults.color_format; // as the pipeline expects
    sg_image const color      = sg_make_image(&cd);
    if (sg_query_image_state(color) != SG_RESOURCESTATE_VALID) return false; // sokol logged why
    sg_view_desc cv{};
    cv.color_attachment.image = color;
    sg_view const colorView   = sg_make_view(&cv);
    sg_pass pass{};
    pass.action.colors[0].clear_value = {0.15f, 0.16f, 0.19f, 1.0f};
    pass.attachments.colors[0]        = colorView;
    draw_floor(app, pass);
    Vec<u8> rgba(default_allocator(), Tag::Io);
    bool const ok =
        read_rgba(color, u32(w), u32(h), rgba) && ex::write_png(app.o.dump, rgba.span(), u32(w), u32(h));
    sg_destroy_view(colorView);
    sg_destroy_image(color);
    if (ok) KILN_INFO("sokol", "wrote %s (%dx%d)", app.o.dump, w, h);
    return ok;
}

// --- sokol_app callbacks -------------------------------------------------------------------------

void init(void* user) {
    App& app = *static_cast<App*>(user);
    // 1. sokol_gfx on the window sokol_app made; the pools hold the adapter's objects and the host's.
    SokolAdapterDesc const ad{};
    sg_desc gd{};
    gd.environment      = sglue_environment();
    gd.logger.func      = slog_func;
    gd.buffer_pool_size = int(ad.maxObjects) + 64;
    gd.image_pool_size  = int(ad.maxObjects) + 64;
    gd.view_pool_size   = int(ad.maxObjects) + 64;
    sg_setup(&gd);

    // 2. The adapter, then the context. Arrays need nothing beyond kArrayTextures: kiln hands the
    //    adapter one upload with every layer, which sokol makes into an image at the next flush.
    Result<SokolAdapter*> sa = sokol_adapter_create(ad, &app.adapter);
    if (sa.failed()) {
        app.exitCode = 2;
        sapp_request_quit();
        return;
    }
    app.sa = *sa;
    ContextDesc cd{};
    cd.diag                  = ex::stdout_diag();
    cd.profiler              = ex::trace_hooks(); // KILN_TRACE=<file>
    cd.adapter               = &app.adapter;
    cd.storeDir              = StrView(app.o.store);
    cd.roots                 = Span<Root const>(app.o.roots, app.o.rootCount);
    cd.hotReload.watchStore  = app.o.watch;
    Result<Context*> created = create(cd);
    if (created.failed()) {
        app.exitCode = 2;
        sapp_request_quit();
        return;
    }
    app.ctx = *created;
#if KILN_SOKOL_HAS_COOK
    cook::ProviderDesc pd{};
    pd.watchSources = app.o.watch;
    app.provider    = cook::install_provider(app.ctx, pd).ok();
#endif

    // 3. The array: a name of its own and the layers in order.
    app.tiles = request_texture_array(
        app.ctx, {.name = "tiles:floor", .layers = Span<StrView const>(kLayers, countof(kLayers))});

    // 4. What the host owns: the shader, its pipeline, a sampler.
    app.shader = sg_make_shader(floor_shader_desc(sg_query_backend()));
    sg_pipeline_desc pd2{};
    pd2.shader        = app.shader;
    pd2.depth.compare = SG_COMPAREFUNC_ALWAYS;
    pd2.label         = "kiln floor";
    app.pipeline      = sg_make_pipeline(&pd2);
    sg_sampler_desc sd{};
    sd.min_filter = sd.mag_filter = sd.mipmap_filter = SG_FILTER_LINEAR;
    app.sampler                                      = sg_make_sampler(&sd);
    app.startMs                                      = ex::ms_since_start();
}

void frame(void* user) {
    App& app = *static_cast<App*>(user);
    if (!app.ctx) return;
    // 5. kiln: the adapter's flush makes this frame's images, then completions and events.
    (void)pump(app.ctx);
    for (Event const& e : events(app.ctx)) {
        KILN_INFO("sokol", "event %-9s v%u", ex::event_name(e.kind), e.version);
        if (e.handle == app.tiles.bits() &&
            (e.kind == EventKind::Ready || e.kind == EventKind::Changed || e.kind == EventKind::Resized))
            log_array(app.ctx, app.tiles);
    }
    // --verify: once the array is Ready, each tile again as a texture of its own, to compare with.
    if (app.verify && app.own[0].is_null() && is_ready(app.ctx, app.tiles))
        for (usize i = 0; i < countof(kLayers); ++i)
            app.own[i] = request_texture(app.ctx, kLayers[i]);

    int const w = sapp_width(), h = sapp_height();
    // Offscreen: one frame after everything settled, dump and/or verify, then quit.
    if (app.o.offscreen && !app.quitting) {
        if (app.settledOnce) {
            if (state(app.ctx, app.tiles) == State::Failed) app.exitCode = 1;
            if (app.exitCode == 0 && app.o.dump && !dump(app, w, h)) app.exitCode = 2;
            if (app.exitCode == 0 && app.verify &&
                !ex::verify_array_layers(app.ctx, app.tiles,
                                         Span<TextureHandle const>(app.own, countof(app.own)),
                                         &read_texture_fn, app.sa))
                app.exitCode = 1;
            app.quitting = true;
        } else if (ex::ms_since_start() - app.startMs > app.o.timeoutS * 1000.0) {
            KILN_ERROR("sokol", "the array did not settle within %u s", app.o.timeoutS);
            app.exitCode = 1;
            app.quitting = true;
        }
        app.settledOnce = settled(app);
        if (app.quitting) sapp_request_quit();
    }

    // 6. Draw into the window.
    sg_pass pass{};
    pass.action.colors[0].clear_value = {0.15f, 0.16f, 0.19f, 1.0f};
    pass.swapchain                    = sglue_swapchain();
    draw_floor(app, pass);
    sg_commit();
}

void cleanup(void* user) {
    App& app = *static_cast<App*>(user);
    ex::log_adapter_stats("sokol", sokol_adapter_stats(app.sa));
    // 7. kiln first (it hands every object back through Adapter::destroy), then sokol.
    if (app.ctx) {
        release(app.ctx, app.tiles);
        for (TextureHandle h : app.own)
            if (!h.is_null()) release(app.ctx, h);
    }
#if KILN_SOKOL_HAS_COOK
    if (app.provider) cook::uninstall_provider(app.ctx);
#endif
    destroy(app.ctx);
    ex::finish_trace();
    sokol_adapter_destroy(app.sa);
    sg_shutdown();
}

void on_event(sapp_event const* e, void*) {
    if (e->type == SAPP_EVENTTYPE_KEY_DOWN && e->key_code == SAPP_KEYCODE_ESCAPE) sapp_request_quit();
}

App g_app; // sokol_app hands its address to every callback

} // namespace

int main(int argc, char** argv) {
    no_crash_dialogs();
    if (int const code = parse(argc, argv, &g_app); code >= 0) return code;
    ex::install_stdout_log();
    sapp_desc d{};
    d.user_data           = &g_app;
    d.init_userdata_cb    = &init;
    d.frame_userdata_cb   = &frame;
    d.cleanup_userdata_cb = &cleanup;
    d.event_userdata_cb   = &on_event;
    d.width               = int(g_app.o.width);
    d.height              = int(g_app.o.height);
    d.window_title        = "kiln-sokol-array";
    d.logger.func         = slog_func;
    sapp_run(&d); // returns after cleanup
    return g_app.exitCode;
}
