// examples/sokol/main.cpp — kiln-sokol: one model and a cube sky through sokol_gfx, with sokol_app
// owning the main loop (docs/design/integration-examples.md). kiln lives in the app callbacks: create()
// in init, pump() (which runs the adapter's flush) and the draw in frame, destroy() in cleanup.
// Meshes are cooked with VertexProfile::Float. The steps a host takes are numbered.
#include "example_app.h"
#include "no_crash_dialogs.h"
#include "readback.h"
#include "sokol_adapter.h"

#include <kiln/assets.h>
#include <kiln/log.h>
#if KILN_SOKOL_HAS_COOK
#include <kiln/cook/provider.h>
#endif

#include "sokol_app.h"
#include "sokol_glue.h"
#include "sokol_log.h"
// Generated by sokol-shdc from scene.glsl: mesh_shader_desc(), sky_shader_desc(), the uniform
// structs and the ATTR_/VIEW_/SMP_/UB_ slot constants.
#include "scene.glsl.h"

#include <cmath>
#include <cstring>

using namespace kiln;
using namespace kiln::sk;
using ex::Mat4;
using ex::Vec3;

namespace {

constexpr f32 kFovY          = 50.0f * ex::kPi / 180.0f;
constexpr u32 kMaxTextures   = 32;
constexpr u32 kMaxLayouts    = 16;
constexpr u32 kMaxParts      = 256;
constexpr int kMaterialViews = 5; // VIEW_base_tex .. VIEW_emissive_tex

struct TextureItem {
    AssetId id = 0;
    TextureHandle handle;
};

struct Background {
    sg_shader shader{};
    sg_pipeline pipeline{};

    void create() {
        shader = sg_make_shader(sky_shader_desc(sg_query_backend()));
        sg_pipeline_desc pd{};
        pd.shader        = shader;
        pd.depth.compare = SG_COMPAREFUNC_ALWAYS;
        pd.label         = "kiln background";
        pipeline         = sg_make_pipeline(&pd);
    }

    /// The caller checks that the environment is present.
    void draw(ex::ViewRays const& rays, f32 exposure, sg_view environment, sg_sampler sampler) const {
        sky_fs_params_t const p{
            .forward = {rays.forward.x, rays.forward.y, rays.forward.z, exposure},
            .right   = {rays.right.x,   rays.right.y,   rays.right.z,   0       },
            .up      = {rays.up.x,      rays.up.y,      rays.up.z,      0       },
        };
        sg_bindings b{};
        b.views[VIEW_sky_tex]   = environment;
        b.samplers[SMP_sky_smp] = sampler;
        sg_apply_pipeline(pipeline);
        sg_apply_bindings(&b);
        sg_range const ub{&p, sizeof p};
        sg_apply_uniforms(UB_sky_fs_params, &ub);
        sg_draw(0, 3, 1);
    }

    void release() {
        sg_destroy_pipeline(pipeline);
        sg_destroy_shader(shader);
    }
};

struct App {
    /// The model content version the materials and geometry were set up for. MetaReady, Changed
    /// and a Ready that follows Failed (a repaired model: reloads emit no MetaReady) carry a new one.
    u32 preparedVersion = 0;
    ex::Options o;
    int exitCode = 0;
    ex::OrbitCamera camera;

    Adapter adapter{};
    SokolAdapter* sa = nullptr;
    Context* ctx     = nullptr;
    bool provider    = false;

    MeshHandle model;
    TextureHandle environment;
    TextureItem textures[kMaxTextures];
    u32 textureCount = 0;

    sg_shader meshShader{};
    sg_pipeline pipelines[kMaxLayouts][2] = {}; ///< per vertex layout, per index type (U16, U32)
    bool unsupported                      = false;
    Background background;
    sg_sampler sampler{}, environmentSampler{};
    /// kiln's placeholders, bound where a material has no texture (sokol wants every slot bound) and
    /// as the sky without one.
    sg_view fallback[kMaterialViews] = {};
    sg_view fallbackCube{};
    Mat4 place;
    Mat4 world[kMaxParts];

    bool settledOnce = false;
    bool quitting    = false; ///< sapp_request_quit() still runs frames until the app ends
    double startMs   = 0;
};

// --- Scene ---------------------------------------------------------------------------------------

TextureHandle find_item(App const& app, AssetId id) {
    for (u32 i = 0; i < app.textureCount; ++i)
        if (app.textures[i].id == id) return app.textures[i].handle;
    return {};
}

void request_textures(App& app, mesh::MeshView const& v) {
    for (u32 i = 0; i < v.textures().size(); ++i) {
        mesh::TextureBinding const& b = v.textures()[i];
        char buf[256];
        StrView const name = texture_asset_name(StrView(app.o.model), v, b, buf, sizeof buf);
        AssetId const id   = asset_id(name);
        if (id == 0 || find_item(app, id) || app.textureCount == kMaxTextures) continue;
        RequestOptions const opt{.textureKind = texture_kind_for_slot(mesh::TextureSlot(b.slot))};
        app.textures[app.textureCount++] = {id, request_texture(app.ctx, name, opt)};
    }
}

/// A pipeline per vertex layout and index type: sokol bakes both into the pipeline.
void build_pipelines(App& app, mesh::MeshView const& v) {
    for (auto& p : app.pipelines)
        for (sg_pipeline& pip : p)
            sg_destroy_pipeline(pip);
    std::memset(app.pipelines, 0, sizeof app.pipelines);
    app.unsupported = false;
    for (u32 li = 0; li < v.layouts().size() && li < kMaxLayouts; ++li) {
        mesh::VertexLayout const& l = v.layouts()[li];
        sg_pipeline_desc d{};
        u32 found = 0;
        for (u32 i = 0; i < l.attribCount; ++i) {
            mesh::VertexAttrib const& a = l.attribs[i];
            if (a.semanticIndex != 0) continue;
            int slot = -1;
            switch (mesh::Semantic(a.semantic)) {
            case mesh::Semantic::Position: slot = ATTR_mesh_pos; break;
            case mesh::Semantic::Normal: slot = ATTR_mesh_normal; break;
            case mesh::Semantic::Tangent: slot = ATTR_mesh_tangent; break;
            case mesh::Semantic::TexCoord: slot = ATTR_mesh_uv; break;
            default: continue;
            }
            d.layout.attrs[slot].buffer_index = int(a.stream);
            d.layout.attrs[slot].offset       = int(a.offset);
            d.layout.attrs[slot].format       = sokol_vertex_format(Format(a.format));
            found |= 1u << slot;
        }
        // The shader reads all four; D3D11 cannot build an input layout with one missing.
        bool const octNormal = d.layout.attrs[ATTR_mesh_normal].format == SG_VERTEXFORMAT_SHORT2N;
        if (found != 0xFu || octNormal) {
            KILN_ERROR("sokol", "%s: needs float position, normal, tangent and UV 0 (profile = \"float\")",
                       app.o.model);
            app.unsupported = true;
            return;
        }
        for (u32 s = 0; s < l.streamCount; ++s)
            d.layout.buffers[s].stride = int(l.strides[s]);
        d.shader              = app.meshShader;
        d.depth.compare       = SG_COMPAREFUNC_LESS_EQUAL;
        d.depth.write_enabled = true;
        d.label               = "kiln mesh";
        d.index_type          = SG_INDEXTYPE_UINT16;
        app.pipelines[li][0]  = sg_make_pipeline(&d);
        d.index_type          = SG_INDEXTYPE_UINT32;
        app.pipelines[li][1]  = sg_make_pipeline(&d);
    }
    mesh::Bounds const& b = v.model().bounds;
    f32 const scale       = b.radius > 0 ? 1.0f / b.radius : 1.0f;
    app.place = ex::scaling(scale) * ex::translation(Vec3{-b.center[0], -b.center[1], -b.center[2]});
}

void handle_event(App& app, Event const& e) {
    bool const isModel = e.asset == AssetKind::Mesh && e.handle == app.model.bits();
    KILN_INFO("sokol", "event %-9s %s v%u", ex::event_name(e.kind), isModel ? "model" : "texture", e.version);
    if (!isModel || e.kind == EventKind::Failed) return;
    mesh::MeshView const* v = mesh_view(app.ctx, app.model);
    if (v && e.version != app.preparedVersion) {
        app.preparedVersion = e.version;
        request_textures(app, *v);
        build_pipelines(app, *v);
    }
}

bool scene_settled(App const& app) {
    if (!ex::settled(state(app.ctx, app.model))) return false;
    if (app.environment && !ex::settled(state(app.ctx, app.environment))) return false;
    for (u32 i = 0; i < app.textureCount; ++i)
        if (!ex::settled(state(app.ctx, app.textures[i].handle))) return false;
    return true;
}

// --- Drawing -------------------------------------------------------------------------------------

/// The material's textures (whatever gpu_object() returns now) in its view slots, and which ones are real.
void bind_material(App const& app, mesh::MeshView const& v, u32 material, sg_bindings& b,
                   mesh_fs_params_t& fs) {
    f32 has[kMaterialViews] = {};
    for (int i = 0; i < kMaterialViews; ++i)
        b.views[i] = app.fallback[i];
    if (material < v.materials().size()) {
        mesh::MaterialSlot const& m = v.materials()[material];
        for (u32 t = 0; t < m.textureCount && m.textureFirst + t < v.textures().size(); ++t) {
            mesh::TextureBinding const& tb = v.textures()[m.textureFirst + t];
            int view                       = -1;
            switch (mesh::TextureSlot(tb.slot)) {
            case mesh::TextureSlot::BaseColor: view = VIEW_base_tex; break;
            case mesh::TextureSlot::Normal: view = VIEW_normal_tex; break;
            case mesh::TextureSlot::MetalRough: view = VIEW_mr_tex; break;
            case mesh::TextureSlot::Occlusion: view = VIEW_occlusion_tex; break;
            case mesh::TextureSlot::Emissive: view = VIEW_emissive_tex; break;
            default: continue;
            }
            char buf[256];
            TextureHandle const h =
                find_item(app, asset_id(texture_asset_name(StrView(app.o.model), v, tb, buf, sizeof buf)));
            sg_view const tex = sokol_texture(app.sa, gpu_object(app.ctx, h));
            if (!tex.id) continue;
            b.views[view] = tex;
            has[view]     = 1.0f;
        }
    }
    fs.has_a[0]                 = has[0];
    fs.has_a[1]                 = has[1];
    fs.has_a[2]                 = has[2];
    fs.has_a[3]                 = has[3];
    fs.has_b[0]                 = has[4];
    ex::MaterialFactors const f = ex::material_factors(v, material);
    std::memcpy(fs.base_color_factor, f.baseColor, sizeof fs.base_color_factor);
    std::memcpy(fs.emissive_normal, f.emissiveNormal, sizeof fs.emissive_normal);
    std::memcpy(fs.mro, f.mro, sizeof fs.mro);
}

/// One frame of the scene into the pass `pass` (the swapchain, or the --dump target).
void draw_scene(App& app, sg_pass const& pass, f32 aspect) {
    sg_begin_pass(&pass);
    ex::View const view = ex::orbit_view(app.camera, Vec3{}, 1.0f, kFovY, aspect);
    Mat4 const viewProj =
        ex::perspective_gl(kFovY, aspect, view.nearZ, view.farZ) * view.view; // see scene.glsl
    f32 const exposure = app.camera.exposure;

    sg_view const sky =
        app.environment ? sokol_texture(app.sa, gpu_object(app.ctx, app.environment)) : sg_view{};
    if (sky.id)
        app.background.draw(ex::view_rays(view.eye, Vec3{}, kFovY, aspect), exposure, sky,
                            app.environmentSampler);

    mesh::MeshView const* v = mesh_view(app.ctx, app.model);
    sg_buffer const buffer  = sokol_buffer(app.sa, gpu_object(app.ctx, app.model)); // invalid until Ready
    if (v && buffer.id && !app.unsupported) {
        mesh_fs_params_t fs{
            .eye               = {view.eye.x, view.eye.y, view.eye.z, exposure},
            .has_a             = {},
            .has_b             = {0, sky.id ? 1.0f : 0.0f, 0, 0},
            .base_color_factor = {}, // bind_material() sets the factors per draw
            .emissive_normal   = {},
            .mro               = {},
        };
        u32 const partCount = min<u32>(v->parts().size(), kMaxParts);
        for (u32 p = 0; p < partCount; ++p) {
            mesh::MeshPart const& part = v->parts()[p];
            Mat4 const local           = ex::from_rt(part.translation, part.rotation);
            app.world[p] =
                part.parent < p ? app.world[part.parent] * local : app.place * local; // parents first
            if (part.lodCount == 0) continue;
            mesh::MeshLod const& lod = v->lods()[part.lodFirst];
            auto const indexType     = mesh::IndexType(lod.indexType);
            if (lod.layout >= kMaxLayouts || indexType == mesh::IndexType::U8)
                continue; // sokol: 16/32 bit only
            sg_apply_pipeline(app.pipelines[lod.layout][indexType == mesh::IndexType::U32 ? 1 : 0]);
            mesh::VertexLayout const& layout = v->layouts()[lod.layout];
            mesh_vs_params_t vs{};
            std::memcpy(vs.model, app.world[p].m, sizeof vs.model);
            std::memcpy(vs.view_proj, viewProj.m, sizeof vs.view_proj);
            sg_range const vsRange{&vs, sizeof vs};
            sg_apply_uniforms(UB_mesh_vs_params, &vsRange);
            for (u32 si = 0; si < lod.submeshCount; ++si) {
                mesh::Submesh const& sm = v->submeshes()[lod.submeshFirst + si];
                sg_bindings b{};
                for (u32 st = 0; st < layout.streamCount; ++st) {
                    b.vertex_buffers[st]        = buffer;
                    b.vertex_buffer_offsets[st] = int(lod.streamOffset[st]);
                }
                b.index_buffer          = buffer;
                b.index_buffer_offset   = int(lod.indexOffset);
                b.views[VIEW_sky_tex]   = sky.id ? sky : app.fallbackCube;
                b.samplers[SMP_smp]     = app.sampler;
                b.samplers[SMP_sky_smp] = app.environmentSampler;
                bind_material(app, *v, sm.material, b, fs);
                sg_apply_bindings(&b);
                sg_range const fsRange{&fs, sizeof fs};
                sg_apply_uniforms(UB_mesh_fs_params, &fsRange);
                sg_draw_ex(int(sm.indexFirst), int(sm.indexCount), 1, sm.vertexBase, 0);
            }
        }
    }
    sg_end_pass();
}

/// Renders one more frame into an image of its own and writes it as a PNG.
bool dump(App& app, int w, int h) {
    sg_image_desc cd{};
    cd.usage.color_attachment = true;
    cd.width                  = w;
    cd.height                 = h;
    cd.pixel_format           = sglue_environment().defaults.color_format; // as the pipelines expect
    sg_image const color      = sg_make_image(&cd);
    sg_image_desc dd{};
    dd.usage.depth_stencil_attachment = true;
    dd.width                          = w;
    dd.height                         = h;
    dd.pixel_format                   = sglue_environment().defaults.depth_format;
    sg_image const depth              = sg_make_image(&dd);
    if (sg_query_image_state(color) != SG_RESOURCESTATE_VALID ||
        sg_query_image_state(depth) != SG_RESOURCESTATE_VALID)
        return false; // sokol logged why
    sg_view_desc cv{}, dv{};
    cv.color_attachment.image         = color;
    dv.depth_stencil_attachment.image = depth;
    sg_view const colorView           = sg_make_view(&cv);
    sg_view const depthView           = sg_make_view(&dv);
    sg_pass pass{};
    pass.action.colors[0].clear_value = {0.15f, 0.16f, 0.19f, 1.0f};
    pass.attachments.colors[0]        = colorView;
    pass.attachments.depth_stencil    = depthView;
    draw_scene(app, pass, f32(w) / f32(h));
    Vec<u8> rgba(default_allocator(), Tag::Io);
    bool ok =
        read_rgba(color, u32(w), u32(h), rgba) && ex::write_png(app.o.dump, rgba.span(), u32(w), u32(h));
    sg_destroy_view(colorView);
    sg_destroy_view(depthView);
    sg_destroy_image(color);
    sg_destroy_image(depth);
    if (ok) KILN_INFO("sokol", "wrote %s (%dx%d)", app.o.dump, w, h);
    return ok;
}

// --- sokol_app callbacks -------------------------------------------------------------------------

void init(void* user) {
    App& app = *static_cast<App*>(user);
    // 1. sokol_gfx on the window sokol_app made.
    // The pools hold the adapter's objects and the host's own (targets, pipelines' views).
    SokolAdapterDesc const ad{};
    sg_desc gd{};
    gd.environment      = sglue_environment();
    gd.logger.func      = slog_func;
    gd.buffer_pool_size = int(ad.maxObjects) + 64;
    gd.image_pool_size  = int(ad.maxObjects) + 64;
    gd.view_pool_size   = int(ad.maxObjects) + 64;
    sg_setup(&gd);

    // 2. The adapter, then the context. create() runs the adapter's flush while it waits for the
    //    placeholders, so it belongs here, after sg_setup().
    Result<SokolAdapter*> sa = sokol_adapter_create(ad, &app.adapter);
    if (sa.failed()) {
        app.exitCode = 2;
        sapp_request_quit();
        return;
    }
    app.sa = *sa;
    ContextDesc cd{};
    cd.diag                  = ex::stdout_diag();
    cd.profiler              = ex::trace_hooks(); // KILN_TRACE=<file>
    cd.adapter               = &app.adapter;
    cd.storeDir              = StrView(app.o.store);
    cd.roots                 = Span<Root const>(app.o.roots, app.o.rootCount);
    cd.hotReload.watchStore  = app.o.watch;
    Result<Context*> created = create(cd);
    if (created.failed()) {
        app.exitCode = 2;
        sapp_request_quit();
        return;
    }
    app.ctx = *created;
#if KILN_SOKOL_HAS_COOK
    if (app.o.rootCount) {
        cook::ProviderDesc pd{};
        pd.meshDefaults.profile = cook::VertexProfile::Float;
        pd.watchSources         = app.o.watch;
        app.provider            = cook::install_provider(app.ctx, pd).ok();
    }
#endif

    // 3. Requests; nothing blocks.
    app.model = request_mesh(app.ctx, StrView(app.o.model));
    if (app.o.sky)
        app.environment =
            request_texture(app.ctx, StrView(app.o.sky), RequestOptions{.textureShape = TextureShape::Cube});

    // 4. What the host owns: shaders, the sky pipeline, samplers. create() waited for the placeholders.
    app.meshShader = sg_make_shader(mesh_shader_desc(sg_query_backend()));
    app.background.create();
    sg_sampler_desc sd{};
    sd.min_filter = sd.mag_filter = sd.mipmap_filter = SG_FILTER_LINEAR;
    sd.max_anisotropy                                = 8;
    app.sampler                                      = sg_make_sampler(&sd);
    sd.wrap_u = sd.wrap_v = sd.wrap_w       = SG_WRAP_CLAMP_TO_EDGE;
    sd.max_anisotropy                       = 1;
    app.environmentSampler                  = sg_make_sampler(&sd);
    TextureKind const kinds[kMaterialViews] = {TextureKind::BaseColor, TextureKind::Normal, TextureKind::Orm,
                                               TextureKind::Orm, TextureKind::Emissive}; // VIEW_* order
    for (int i = 0; i < kMaterialViews; ++i)
        app.fallback[i] = sokol_texture(app.sa, placeholder_object(app.ctx, kinds[i]));
    app.fallbackCube =
        sokol_texture(app.sa, placeholder_object(app.ctx, TextureKind::Emissive, TextureShape::Cube));
    app.startMs = ex::ms_since_start();
}

void frame(void* user) {
    App& app = *static_cast<App*>(user);
    if (!app.ctx) return;
    // 5. kiln: the adapter's flush makes this frame's images and buffers, then completions,
    //    and events. Nothing here waits.
    (void)pump(app.ctx);
    for (Event const& e : events(app.ctx))
        handle_event(app, e);

    int const w = sapp_width(), h = sapp_height();
    // Offscreen: one frame after the scene settled (as the GL examples do), dump and quit.
    // sokol_app keeps calling frame() until it ends the loop, hence `quitting`.
    if (app.o.offscreen && !app.quitting) {
        if (app.settledOnce) {
            if (app.o.dump && !dump(app, w, h)) app.exitCode = 2;
            if (state(app.ctx, app.model) == State::Failed && app.exitCode == 0) app.exitCode = 1;
            app.quitting = true;
        } else if (ex::ms_since_start() - app.startMs > app.o.timeoutS * 1000.0) {
            KILN_ERROR("sokol", "the scene did not settle within %u s", app.o.timeoutS);
            app.exitCode = 1;
            app.quitting = true;
        }
        app.settledOnce = scene_settled(app);
        if (app.quitting) sapp_request_quit();
    }

    // 6. Draw into the window.
    sg_pass pass{};
    pass.action.colors[0].clear_value = {0.15f, 0.16f, 0.19f, 1.0f};
    pass.swapchain                    = sglue_swapchain();
    draw_scene(app, pass, h > 0 ? f32(w) / f32(h) : 1.0f);
    sg_commit();
}

void cleanup(void* user) {
    App& app = *static_cast<App*>(user);
    ex::log_adapter_stats("sokol", sokol_adapter_stats(app.sa));
    // 7. kiln first (it hands every object back through Adapter::destroy), then sokol.
#if KILN_SOKOL_HAS_COOK
    if (app.provider) cook::uninstall_provider(app.ctx);
#endif
    destroy(app.ctx);
    ex::finish_trace();
    sokol_adapter_destroy(app.sa);
    app.background.release();
    sg_shutdown();
}

void on_event(sapp_event const* e, void* user) {
    ex::OrbitCamera& c = static_cast<App*>(user)->camera;
    switch (e->type) {
    case SAPP_EVENTTYPE_MOUSE_DOWN:
        c.dragging = c.dragging || e->mouse_button == SAPP_MOUSEBUTTON_LEFT;
        break;
    case SAPP_EVENTTYPE_MOUSE_UP:
        if (e->mouse_button == SAPP_MOUSEBUTTON_LEFT) c.dragging = false;
        break;
    case SAPP_EVENTTYPE_MOUSE_MOVE:
        if (!c.dragging) break;
        c.azimuth -= e->mouse_dx * 0.01f;
        c.elevation = clamp(c.elevation + e->mouse_dy * 0.01f, -1.5f, 1.5f);
        break;
    case SAPP_EVENTTYPE_MOUSE_SCROLL:
        c.zoom = clamp(c.zoom * std::pow(0.9f, e->scroll_y), 0.05f, 20.0f);
        break;
    case SAPP_EVENTTYPE_KEY_DOWN:
        if (e->key_code == SAPP_KEYCODE_ESCAPE) sapp_request_quit();
        if (e->key_code == SAPP_KEYCODE_EQUAL || e->key_code == SAPP_KEYCODE_KP_ADD) c.exposure += 0.5f;
        if (e->key_code == SAPP_KEYCODE_MINUS || e->key_code == SAPP_KEYCODE_KP_SUBTRACT) c.exposure -= 0.5f;
        break;
    default: break;
    }
}

App g_app; // large; sokol_app hands its address to every callback

} // namespace

int main(int argc, char** argv) {
    no_crash_dialogs();
    if (int const code = ex::parse_options("kiln-sokol", argc, argv, &g_app.o); code >= 0) return code;
    ex::install_stdout_log();
    sapp_desc d{};
    d.user_data           = &g_app;
    d.init_userdata_cb    = &init;
    d.frame_userdata_cb   = &frame;
    d.cleanup_userdata_cb = &cleanup;
    d.event_userdata_cb   = &on_event;
    d.width               = int(g_app.o.width);
    d.height              = int(g_app.o.height);
    d.window_title        = "kiln-sokol";
    d.logger.func         = slog_func;
    sapp_run(&d); // returns after cleanup
    return g_app.exitCode;
}
