#!/usr/bin/env python3
"""Generates kiln's small JPEG/WebP image corpus for cook/image.h decode tests.

Needs Pillow (`pip install Pillow`); everything else is standard library. Deterministic:
every pixel comes from a fixed formula (no randomness, no timestamps), so re-running
reproduces every file byte-for-byte for a given Pillow/libjpeg/libwebp build.

Run from anywhere:  python tests/corpus/images/generate.py
Output: tests/corpus/images/*.jpg, *.webp (committed corpus files) and
        tests/image_fixtures.h (the same bytes, plus source pixels, as C++ arrays).

tests/corpus/gltf/generated/generate.py reads jpeg_gradient_rgb.jpg from this directory
(stdlib only, no Pillow) to embed a JPEG texture in a GLB; keep that file's name stable.
"""
import os
from PIL import Image

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER_PATH = os.path.join(OUT_DIR, "..", "..", "image_fixtures.h")


def fx(x, w):
    return x / (w - 1) if w > 1 else 0.0


def gradient_rgb_pixels(w, h):
    """Smooth RGB gradient: R across x, G across y, B along the diagonal."""
    px = bytearray()
    for y in range(h):
        for x in range(w):
            sx, sy = fx(x, w), fx(y, h)
            px += bytes(
                (
                    round(sx * 255),
                    round(sy * 255),
                    round((sx + sy) / 2 * 255),
                )
            )
    return bytes(px)


def gradient_gray_pixels(w, h):
    px = bytearray()
    for y in range(h):
        for x in range(w):
            sx, sy = fx(x, w), fx(y, h)
            px.append(round((sx + sy) / 2 * 255))
    return bytes(px)


def gradient_rgba_pixels(w, h):
    """RGB as gradient_rgb_pixels; alpha varies from 32 to 255 toward the (max x, max y)
    corner. Never fully transparent: a lossless WebP encoder is free to store any RGB it
    likes under alpha=0 (the color is unobservable), which would make an exact-pixel
    decode check meaningless."""
    px = bytearray()
    for y in range(h):
        for x in range(w):
            sx, sy = fx(x, w), fx(y, h)
            px += bytes(
                (
                    round(sx * 255),
                    round(sy * 255),
                    round((sx + sy) / 2 * 255),
                    32 + round((1.0 - sx) * (1.0 - sy) * 223),
                )
            )
    return bytes(px)


class Fixture:
    def __init__(self, cname, filename, width, height, channels, pixels, file_bytes):
        self.cname = cname  # C++ identifier stem, e.g. "JpegGradientRgb"
        self.filename = filename
        self.width = width
        self.height = height
        self.channels = channels
        self.pixels = pixels  # reference source pixels, row-major, `channels` bytes/pixel
        self.file_bytes = file_bytes


def make_jpeg(cname, filename, w, h, mode, pixels, progressive=False):
    img = Image.frombytes(mode, (w, h), pixels)
    path = os.path.join(OUT_DIR, filename)
    img.save(
        path,
        format="JPEG",
        quality=95,
        subsampling=0,
        progressive=progressive,
        optimize=False,
    )
    with open(path, "rb") as fh:
        data = fh.read()
    channels = 1 if mode == "L" else 3
    print(f"  {filename}: {len(data)} bytes ({w}x{h}, {channels}ch, {'progressive' if progressive else 'baseline'})")
    return Fixture(cname, filename, w, h, channels, pixels, data)


def make_webp(cname, filename, w, h, mode, pixels, lossless, quality=None):
    img = Image.frombytes(mode, (w, h), pixels)
    path = os.path.join(OUT_DIR, filename)
    kwargs = {"format": "WEBP", "lossless": lossless}
    if quality is not None:
        kwargs["quality"] = quality
    img.save(path, **kwargs)
    with open(path, "rb") as fh:
        data = fh.read()
    channels = 4 if mode == "RGBA" else 3
    print(f"  {filename}: {len(data)} bytes ({w}x{h}, {channels}ch, {'lossless' if lossless else 'lossy'})")
    return Fixture(cname, filename, w, h, channels, pixels, data)


def write_byte_array(out, name, data):
    out.append(f"inline constexpr unsigned char {name}[] = {{")
    line = "   "
    for i, b in enumerate(data):
        chunk = f" 0x{b:02x},"
        if len(line) + len(chunk) > 116:
            out.append(line)
            line = "   "
        line += chunk
    if line.strip():
        out.append(line)
    out.append("};")


def write_header(fixtures):
    out = []
    out.append("// tests/image_fixtures.h — generated by tests/corpus/images/generate.py: do not edit by hand.")
    out.append("// JPEG/WebP corpus bytes plus their reference source pixels (row-major, top-left origin).")
    out.append("#pragma once")
    out.append("")
    out.append("namespace kiln::test::img {")
    out.append("")
    for fx_ in fixtures:
        out.append(f"// {fx_.filename}: {fx_.width}x{fx_.height}, {fx_.channels} channel(s), 8-bit.")
        out.append(f"inline constexpr unsigned kW{fx_.cname} = {fx_.width};")
        out.append(f"inline constexpr unsigned kH{fx_.cname} = {fx_.height};")
        out.append(f"inline constexpr unsigned kC{fx_.cname} = {fx_.channels};")
        write_byte_array(out, f"k{fx_.cname}Bytes", fx_.file_bytes)
        write_byte_array(out, f"k{fx_.cname}Pixels", fx_.pixels)
        out.append("")
    out.append("} // namespace kiln::test::img")
    out.append("")
    text = "\n".join(out)
    with open(HEADER_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {os.path.abspath(HEADER_PATH)}: {len(text)} bytes")


def main():
    print("Generating image corpus into", OUT_DIR)
    fixtures = []

    w, h = 16, 8
    fixtures.append(
        make_jpeg("JpegGradientRgb", "jpeg_gradient_rgb.jpg", w, h, "RGB", gradient_rgb_pixels(w, h))
    )

    w, h = 8, 8
    fixtures.append(make_jpeg("JpegGray", "jpeg_gray.jpg", w, h, "L", gradient_gray_pixels(w, h)))

    w, h = 16, 16
    fixtures.append(
        make_jpeg(
            "JpegProgressive",
            "jpeg_progressive.jpg",
            w,
            h,
            "RGB",
            gradient_rgb_pixels(w, h),
            progressive=True,
        )
    )

    w, h = 8, 8
    fixtures.append(
        make_webp(
            "WebpLosslessRgba",
            "webp_lossless_rgba.webp",
            w,
            h,
            "RGBA",
            gradient_rgba_pixels(w, h),
            lossless=True,
        )
    )

    w, h = 16, 16
    fixtures.append(
        make_webp(
            "WebpLossyRgb",
            "webp_lossy_rgb.webp",
            w,
            h,
            "RGB",
            gradient_rgb_pixels(w, h),
            lossless=False,
            quality=80,
        )
    )

    write_header(fixtures)
    total = sum(os.path.getsize(os.path.join(OUT_DIR, f)) for f in os.listdir(OUT_DIR) if f.endswith((".jpg", ".webp")))
    print(f"Total corpus size in {OUT_DIR}: {total} bytes")


if __name__ == "__main__":
    main()
